server:
  port: ${port:9091}
spring:
  application:
    name: eureka-client-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&userSSL=false&serverTimezone=UTC
    username: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
 
 test: 
  name: github
